### ISSUE TITLE
Error: No such object: dockerinspect.json

### ISSUE THREAD

**Issue by phillijw** [nexdrew/rekcod#38]
When I send inspect output to a json file and then use rekcod, I get empty output and then it complains about no such object.

This is using the docker installation with an alias.

```
phillijw@computer:~$ ls *.json
dockerinspect.json
phillijw@computer:~$ rekcod dockerinspect.json
[]

Error: No such object: dockerinspect.json

phillijw@computer:~$
```

**Comment by nexdrew** [comment]
I suspect this is because you'd have to mount `pwd` in order for the rekcod container to be able to read a file in the current working directory.

Try something like this instead:

```console
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/home nexdrew/rekcod /home/dockerinspect.json
```

**Comment by phillijw** [comment]
That fixes it, thanks

**Comment by nexdrew** [comment]
Cool, no problem, thanks for reporting!
