### ISSUE TITLE
conflicting options hostname and the network mode / sh -c not properly quoted

### ISSUE THREAD

**Issue by KevinWang15** [nexdrew/rekcod#40]
Thanks for the great tool!

Two minor problems:

1. docker says `Conflicting options: hostname and the network mode.`
when `.HostConfig.NetworkMode == "host",` and `.Config.Hostname` is set

2. when `.Config.Cmd` is `["sh", "-c", "(a -a) \u0026\u0026 (b -b)"]`, generated command is `sh -c (a -a) && (b -b)`, but it should be `sh -c '(a -a) && (b -b)'` (with quotes)

**Comment by nexdrew** [comment]
@KevinWang15 Apologies! Somehow I let this issue slip through the cracks. Thanks for reporting!

In the first scenario, it sounds like rekcod should ignore `Config.Hostname` when `HostConfig.NetworkMode` is `"host"` - does that sound correct?

In the second scenario, you're absolutely right, thanks for the example! I'm not quite sure how to know when it's appropriate to wrap each `Config.Cmd` element in quotes. It looks like it might be safe to _always_ wrap each element (e.g. output `'sh' '-c' '(a -a) && (b -b)'`), but do you have any suggestions?

**Comment by KevinWang15** [comment]
For the second problem, my idea is that if the argument does not contain any of the following characters, then it needs not be escaped 
```
!"#$&'( )*,;<>?[\]^`{|}
```
reference: https://stackoverflow.com/a/44581064/6247478

I shall take a take a further look into the first problem

**Comment by nexdrew** [comment]
Ok nice, that gives us something to work with, thanks.

For the host problem, I was basing my suggestion what I found here: https://docs.docker.com/network/host/

**Comment by KevinWang15** [comment]
I'm no longer sure of the first problem, I cannot reproduce it on docker 18.09.6 now.
`--network host -h ubuntu` works just fine. Maybe it's related to the docker version I was using then (it was an old version).

The [docs](https://docs.docker.com/engine/reference/run/) only stated that 
> --hostname is invalid in host UTS mode

`--uts host -h ubuntu` produces `conflicting options: hostname and the UTS mode.`
So just make sure when `.HostConfig.UTSMode` is set to `host`, `.Config.Hostname` is ignored. (I've verified it)

**Comment by nexdrew** [comment]
Just wanted to let you know that these issues have been fixed in the current version:

- `rekcod@3.0.0` (or `rekcod@latest`) on npm
- `nexdrew/rekcod:3.0.0` (or `nexdrew/rekcod:latest`) on docker hub

Feel free to give it a shot, and thanks for reporting!
