### ISSUE TITLE
--privileged not supported

### ISSUE THREAD

**Issue by d33tah** [nexdrew/rekcod#49]
I actually got to try out the tool. In addition to hitting #40, I noticed a problem with one of my containers not working because it relied on `--privileged`. Thought I'd let you know it's something I'm currently missing.

**Comment by nexdrew** [comment]
Ok, thanks for reporting! Should be able to get this fixed soon-ish.

**Comment by nexdrew** [comment]
Just wanted to let you know that support for the `--privileged` flag has been added and published as:

- `rekcod@3.0.0` (or `rekcod@latest`) on npm
- `nexdrew/rekcod:3.0.0` (or `nexdrew/rekcod:latest`) on docker hub

Feel free to give it a shot.
