### ISSUE TITLE
Many of the docker arguments are not generated

### ISSUE THREAD

**Issue by leodotcloud** [nexdrew/rekcod#56]
1) `--security-opt`

Create container with `--security-opt` set. 
Run rekcod, it doesn't generate the command with this argument.
Reference: https://docs.docker.com/engine/security/apparmor/

2) `--pid=host`

3) `--privileged`

**Comment by acutchin-bitpusher** [comment]
also --group-add

**Comment by nexdrew** [comment]
Sorry for the long delay, but thanks for reporting this!

Just wanted to let you know that support for the flags you mentioned have been added and published as:

- `rekcod@3.0.0` (or `rekcod@latest`) on npm
- `nexdrew/rekcod:3.0.0` (or `nexdrew/rekcod:latest`) on docker hub

Feel free to give it a shot.

If there are other `docker run` arguments you need, please report those too.

Thanks again for your feedback, and thanks for using `rekcod`!
